language: python
python:
- "2.7"
- "3.6"
install:
- pip install -r requirements.txt --upgrade
- pip install pylint wheel --upgrade
script:
- nosetests
- pylint txoauth2 tests example/main.py --rcfile=.pylint.rc
before_deploy:
- >
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    python setup.py bdist_wheel --universal;  
  fi
deploy:
- provider: releases
  api_key:
    secure: "meFITthVe9xTwW0vuLqT/A+qBsR5/8tB0bZlSI79FAvkAWSTgdTRtTjwDNEFmYxK6GgW+GJncALLLlolCSmeXhfRyRl/NeM7aWXLHYLyQpNKd3akK0sGwzLBJXJrOoh8phSMBRy6HeB63urmxka6h+xp0UfN+0TWyKb3YK76pysDHDk2wmSFhoGQS/BFUPoLncb9kHQUcNYX7WxGItqyxn8LpgdE115RnfMzFUfX2N3kwrqzVBA0f0QTDzDXxKIBOzayTLfvqomHiFaP+BHlPerUTEb/V3QpYUDH8E//gJzP87QvDxm677x8/M2Tyv+WEpL08+fJJg/gWwO9gOqdjeFiVHj3X3ut/0omNJ5myN1hL6Vm/EGk7h7qyXDswl9FpWskD6alRG4U+ixLnpzVBWRRnpQMPR2YXia/BxaEAws/8jf4DlP0ZMMViQLMZkQqJtpEQWgOjiHVtQO+e2GNw54Spkkw3z7ALIv2PEWq8ZmOhgeyI/OKcNcGwjxF4jr/ceNUgjI66OAYFdhMOZnjoh95W1VcertB1HZHOw8GG7BJvuM/jVrCbhnRU2zCGO9d6oKJaw2Y5s5WIUPcSomMK9UH1zOBsJijFNWT2jq6o/3ZHrtFwEJk8kJa9zwfVnMjMr0sWFXzmG3OA8430rvQjA0krWKiZJbj+UFPnV9EESI="
  file_glob: true
  file: "dist/txoauth2-*-py2.py3-none-any.whl"
  skip_cleanup: true
  on:
    tags: true
    branch: master
- provider: pypi
  user: "Abestanis"
  password:
    secure: "G9rFrItBnhocdkAisxcgldovr1N4EsSyr9vpsxSxQaUBMeSgaIPAj7NjXMqU8pvmtEa9ZVoDYY0mtzveT+XY2NBy8X9bm2r+FB0rOZmHSuZjruA2fd+nVtmQtOBDBPtCUnE4UIJUBQ5AjpZeiwum+95rpRYtTL47eaSxBX73CGWrfdX69TB2pUShG37AQZM3pRdT09CoTEKEmzp5D+2KOL39JIdZNp0pWk6Mfk7q5QDl5YLGETg1yjelz9fHiWrx7o2G2XIIFRsuFjZntAJ57tljRPTnmlC/V3y5Uz8TMuj24CRZX1194sXRv9Tdt5E0Dbc3yo2WVqHWpkPpC/oCBEPzJPuJM4kAqkC5TvojZipxVOt3KwxlYstzLz6c+6DZVjYvn3+Vvu0TlnNtz8EPEkAyv0cLsgZUh94RHqFSCk6QnaNE9HymU63EPFfYLlLOe2KRw6XJ6tmXLM0z7blX6PR7tUhze3lOddGfGWPiA28lrAiLfmWtICVvwngSXEWpt4U/0IMOlkIzwoki8xr16RnLEm1br7FDnH4mMm732bOFmbUaiTOp82DhsdAaKFs3TLQS65uA4LWE4WwZKwH6VhgMAAwFljUdPWvTWq7vSiDcIfTjh+EHDaPMF3g8kkhpTRdxrGmzj0ifH4utcJSMr7SvkrJS56Ecn0FG3cSmQH0="
  distributions: "bdist_wheel"
  skip_existing: true
  on:
    tags: true
    branch: master
