name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
      - name: Create wheel
        run: python setup.py bdist_wheel --universal
      - name: Publish 📦 to Github
        uses: softprops/action-gh-release@v1
        with:
          files: dist/txoauth2-*-py2.py3-none-any.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
