name: Deploy

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
      - name: Create wheel
        run: python setup.py bdist_wheel --universal
      - name: Publish 📦 to Github
        uses: softprops/action-gh-release@v1
        with:
          files: dist/txoauth2-*-py2.py3-none-any.whl
          body_path: changelogs/current.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
      - name: Determine new version string
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Archive changelog
        run: |
          mv changelogs/current.txt changelogs/${{ env.RELEASE_VERSION }}.txt
          echo -n -e "\n" > current.txt
      - name: Push archived changelog 
        uses: EndBug/add-and-commit@v
